name: SVG to PNG Converter

on:
  push:
    paths:
      - '**.svg'
  workflow_dispatch:

permissions:
  contents: write  # 关键权限声明

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}  # 优先使用 PAT
        fetch-depth: 0

    # ... (保持之前的安装和转换步骤)

    - name: Commit and push
      run: |
        # 配置 git 身份
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        # 同步最新代码（处理分支保护）
        git pull origin ${{ github.ref_name }} --rebase
        
        # 只添加 png_output 目录
        git add png_output/
        
        # 提交并推送
        if ! git diff-index --quiet HEAD --; then
          git commit -m "Auto: 生成 PNG 文件 [skip ci]"
          git push origin HEAD:${{ github.ref_name }}
        else
          echo "没有需要提交的更改"
        fi
